export const LETTER1: { [key: string]: string } = {
  "\\alpha": "α",
  "\\beta": "β",
  "\\chi": "χ",
  "\\delta": "δ",
  "\\epsilon": "ϵ",
  "\\varepsilon": "ε",
  "\\eta": "η",
  "\\gamma": "γ",
  "\\iota": "ι",
  "\\kappa": "κ",
  "\\lambda": "λ",
  "\\mu": "μ",
  "\\nu": "ν",
  "\\omega": "ω",
  "\\phi": "ϕ",
  "\\varphi": "φ",
  "\\pi": "π",
  "\\psi": "ψ",
  "\\rho": "ρ",
  "\\sigma": "σ",
  "\\varsigma": "ς",
  "\\tau": "τ",
  "\\theta": "θ",
  "\\vartheta": "ϑ",
  "\\upsilon": "υ",
  "\\xi": "ξ",
  "\\zeta": "ζ",
};

export const LETTER2: { [key: string]: string } = {
  "\\Delta": "Δ",
  "\\Gamma": "Γ",
  "\\Lambda": "Λ",
  "\\Omega": "Ω",
  "\\Phi": "Φ",
  "\\Pi": "Π",
  "\\Psi": "Ψ",
  "\\Sigma": "Σ",
  "\\Theta": "Θ",
  "\\Upsilon": "Υ",
  "\\Xi": "Ξ",
};
