name: "ci"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test
